# Generated by Django 4.0.3 on 2022-03-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_remove_evento_data_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='data_evento',
            field=models.DateField(null=True),
        ),
    ]
